name: "cloud-storage-prod"

services:
  nginx_storage:
    image: 'nginx:alpine'
    container_name: "nginx_storage"
    restart: "always"
    networks:
      - storage-network
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - storage-app
  db_storage:
    image: 'olegarholeg/postgres:16-alpine'
    container_name: "db_storage"
    restart: "always"
    networks:
      - storage-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    shm_size: '64mb'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_storage"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis_storage:
    image: 'olegarholeg/redis:7-alpine'
    container_name: "redis_storage"
    restart: "always"
    networks:
      - storage-network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: "olegarholeg/minio:latest"
    container_name: minio
    restart: always
    networks:
      - storage-network
    ports:
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    command: server /data --address ":9000" --console-address ":9001"
  storage-app:
    image: "olegarholeg/storage-app"
    container_name: "storage-app"
    restart: "always"
    networks:
      - storage-network
    ports:
      - "127.0.0.1:8090:8090"
    depends_on:
      db_storage:
        condition: service_healthy
      redis_storage:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
networks:
  storage-network:
    driver: bridge
    name: storage-network
volumes:
  pgdata:
  minio_data:
