services:
  db_storage:
    image: 'olegarholeg/postgres:16-alpine'
    container_name: "db_storage"
    restart: "always"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_storage
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_storage"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis_storage:
    image: 'olegarholeg/redis:7-alpine'
    container_name: "redis_storage"
    restart: "always"
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: "olegarholeg/minio:latest"
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --address ":9000" --console-address ":9001"
networks:
  storage-network:
    driver: bridge
volumes:
  pgdata:
  minio_data: